routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/apitest/{project_id}', 'ApiTestController@apitest')->name('apitest');

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('clients','ClientsController');

Route::resource('projects', 'ProjectsController');

app/Client.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    protected $fillable = [

        'url','project','verb','input'

    ];

    public function projects(){
        
        return $this->belongsTo('App\Project');
    }
}

app/Http/Controllers/ClientsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Client;
use App\Project;

class ClientsController extends Controller
{
        /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $clients=Client::all();
        $projects=Project::get();
        return view('clients.index',compact('clients', 'projects'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $projects=Project::get();
        return view('clients.create',compact('projects'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        request()->validate([

            'url' => 'required',
            'input' => 'required',
            'verb' => 'required',
            'project_id' => 'required'
            
            

        ]);



        Client::create($request->all());


            return redirect()->route('clients.index')

                 ->with('success','Client created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $client = Client::find($id);
        $projects=Project::get();
        return view('clients.edit',compact('client','id','projects'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    
    {
        $client= Client::find($id);
        $client->url=$request->get('url');
        $client->project_id=$request->get('project_id');
        $client->verb=$request->get('verb');
        $client->input=$request->get('input');
        $client->save();
        return redirect('clients');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $client = Client::find($id);
        $client->delete();
        return redirect('clients')->with('success','Information has been  deleted');
    }
}

resources/views/clients/create.blade.php
@extends('layouts.app')

@section('content')

  <div class="container">
    <div class="row justify-content-center">
        <div class="col-md-4">
            <div class="card border-info mb-3">
                <div class="card-header bg-info text-white text-center" style="font-size: 14px;"><b>REGISTER API HERE</b></div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    <form action="{{ route('clients.store') }}" method="POST">
                        @csrf

                        <div class="form-group">
                          <label for="Url">Url:</label>
                          <textarea class="form-control" id="url" name="url" rows="3"></textarea>
                        </div>

                        <div class="form-group">
                          <label for="Input">Input:</label>
                          <textarea class="form-control" id="input" name="input" rows="3"></textarea>
                        </div>

                        <div class="form-group">
                          <label for="Verb">Verb:</label>
                          <select class="form-control" name="verb">
                              <option value="GET">GET</option>
                              <option value="POST">POST</option>
                            </select>
                        </div>

                        <div class="form-group ">
                          <label for="Project">Project:</label>
                          <select class="form-control" name="project_id">
                                    @foreach ($projects as $project)
                                        <option>{{ $project->id }}</option>
                                    @endforeach
                          </select>
                        </div>

                        <div class="form-group">
                            <div class="text-center">
                                <button class="btn btn-success" type="submit">Submit</button>
                            </div>
                        </div>

                    </form>

                </div>
            </div>
        </div>
    </div>

  </div>

@endsection


    

resources/views/clients/edit.blade.php
@extends('layouts.app')

@section('content')

  <div class="container">
    <div class="row justify-content-center">
        <div class="col-md-4">
            <div class="card border-info mb-3">
                <div class="card-header bg-info text-white text-center" style="font-size: 14px;"><b>EDIT API HERE</b></div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    <form action="{{ route('clients.update', ['id' => $client->id]) }}" method="POST">

                          @csrf

                          @method('PUT')

                        <div class="form-group">
                          <label for="Url">Url:</label>
                          <textarea class="form-control" name="url" rows="3">{{$client->url}}</textarea>
                        </div>

                        <div class="form-group">
                          <label for="Input">Input:</label>
                          <textarea class="form-control" name="input" rows="3">{{$client->input}}</textarea>
                        </div>

                        <div class="form-group">
                          <label for="Verb">Verb:</label>
                          <select name="verb">
                            <option value="GET" @if($client->verb=="GET") selected @endif>GET</option>
                            <option value="POST" @if($client->verb=="POST") selected @endif>POST</option>
                          </select>
                        </div>

                        <div class="form-group ">
                          <label for="Project">Project:</label>
                          <select class="form-control" name="project_id">
                                @foreach ($projects as $project)
                                    <option value="{{ $project->id }}">{{ $project->id }}</option>
                                @endforeach
                          </select>
                        </div>

                        <div class="form-group">
                            <div class="text-center">
                                <button class="btn btn-success" type="submit">Update</button>
                            </div>
                        </div>

                    </form>

                </div>
            </div>
        </div>
    </div>

  </div>

@endsection


    

resources/views/clients/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
              @if ($message = Session::get('success'))

                  <div class="alert alert-success alert-dismissible fade show" role="alert">

                      <p>{{ $message }}</p>
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                  </div>

              @endif
      <br>
          <div class="row">

        <div class="col-lg-12 margin-tb">

            <span class="float-left">

                <h2>Automated API Tester</h2>

            </span>

            <span class="float-right">

                <a class="btn btn-success" href="{{ route('clients.create') }}"> Register A New API</a>

            </span>

        </div>

    </div>
   <br>
  <div class="container">
    <h3>Click a Project to Test It's API's</h3><br>
    <i class="fas fa-hand-point-down fa-2x faa-parent animated faa-fast faa-bounce" style="color: #219dbc"></i> 
    <ol class="rectangle-list">
      @foreach($projects as $project)
      <li><a href="{{route('apitest',['project' => $project->id])}}">{{$project->name}}</a></li> 
      @endforeach                                             
    </ol>
  </div>

  <br>
  <h3>Available Projects and Their API's</h3><br>
  <div class="accordion" id="accordion">
  <div class="card">
    <div class="card-header" id="project_id">
      <h3>
        <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          {{$project->name}}
        </button>
      </h3>
    </div>

    <div id="collapseOne" class="collapse show" aria-labelledby="project_id" data-parent="#accordion">
      <div class="card-body">
          <table class="table table-striped">
    <thead>
      <tr>
        <th>ID</th>
        <th>URL</th>
        <th>VERB</th>
        <th>INPUT</th>
        <th>PROJECT ID</th>
        <th colspan="2">Action</th>
      </tr>
    </thead>
    <tbody>
      
      @foreach($clients as $client)
      <tr>
        <td>{{$client['id']}}</td>
        <td><a href="{{$client['url']}}">{{$client['url']}}</a></td>
        <td>{{$client['verb']}}</td>
        <td>{{$client['input']}}</td>
        <td>{{$client['project_id']}}</td>
        
        <td><a href="{{ route('clients.edit', ['client' => $client->id]) }}" class="btn btn-warning">Edit <i class="far fa-edit"></i></a></td>
        <td>
          <form action="{{ route('clients.destroy', ['client' => $client->id ]) }}" method="post">
            @csrf
            @method('DELETE')

            <button class="btn btn-danger" type="submit">Delete <i class="far fa-trash-alt"></i></button>
          </form>
        </td>
      </tr>
      @endforeach
    </tbody>
  </table>
      </div>
    </div>
  </div>
</div>
</div>
@endsection